import { describe, expect, it } from 'vitest';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { findTool, invokeTool, type ToolCtx } from '../src/tools/registry.js';
import { BloxConfigSchema } from '../src/config.js';
import { MODEL_LOADER_PATH, MODEL_LOADER_SOURCE, npcProgram, planModelLoader, wireModelProgram } from '../src/anim/npc.js';
import { luneBin, luneCheck } from './helpers/lune.js';
import type { StudioSession } from '../src/studio/session.js';

const envelope = (v: unknown) => ({ content: [{ type: 'text', text: JSON.stringify({ ok: true, n: 1, values: { v1: JSON.stringify(v) }, logs: [] }) }] });
function ctx(reply: (code: string) => unknown, codes: string[] = []): ToolCtx {
  const session = { call: async (n: string, a: Record<string, unknown>) => { codes.push(`${n}:${String(a.code ?? '')}`); return envelope(reply(String(a.code ?? ''))); } } as unknown as StudioSession;
  const projectPath = mkdtempSync(join(tmpdir(), 'blox-npc-'));
  return { session, projectPath, config: BloxConfigSchema.parse({ projectPath }), agent: 'test' };
}
const call = (args: Record<string, unknown>, c: ToolCtx) => invokeTool(findTool('animate')!, args, c);

describe('the model loader', () => {
  it('drives every tagged model from its attributes', () => {
    expect(MODEL_LOADER_SOURCE).toMatch(/local TAG = "BloxAnimated"/);
    expect(MODEL_LOADER_SOURCE).toMatch(/GetInstanceAddedSignal\(TAG\)/);
    expect(MODEL_LOADER_SOURCE).toMatch(/BloxAnim_/);
    expect(MODEL_LOADER_SOURCE).toMatch(/SLOWEST, FASTEST = 0\.5, 2/);
    expect(MODEL_LOADER_SOURCE.split('\n')[0]).toMatch(/^-- GENERATED by blox/);
  });
  it('times a model without a PrimaryPart from its pivot', () => {
    expect(MODEL_LOADER_SOURCE).toMatch(/model:GetPivot\(\)\.Position/);
  });
  it('a hand-edited loader is refused; CRLF is still ours', () => {
    const P = mkdtempSync(join(tmpdir(), 'blox-npcl-'));
    expect(planModelLoader(P)).toEqual({ ok: true, write: true });
    const f = join(P, MODEL_LOADER_PATH);
    mkdirSync(dirname(f), { recursive: true });
    writeFileSync(f, MODEL_LOADER_SOURCE.replace(/\n/g, '\r\n'));
    expect(planModelLoader(P)).toEqual({ ok: true, write: false });
    writeFileSync(f, MODEL_LOADER_SOURCE + '\n-- mine');
    expect(planModelLoader(P)).toMatchObject({ ok: false, error: expect.stringMatching(/edited by hand/) });
  });
  it.skipIf(!luneBin())('loader and npc program compile', () => {
    const d = mkdtempSync(join(tmpdir(), 'blox-npcluau-'));
    writeFileSync(join(d, 'loader.luau'), MODEL_LOADER_SOURCE);
    writeFileSync(join(d, 'npc.luau'), npcProgram({ name: 'Guard', rig: 'R15', at: [0, 0, 0], parent: 'Workspace' }));
    writeFileSync(join(d, 'wire_model.luau'), wireModelProgram({ path: 'Workspace.Guard', state: 'walk', id: 'rbxassetid://1', speed: 3, allowed: [], force: false, rigType: 'R15' }));
    expect(luneCheck([join(d, 'loader.luau'), join(d, 'npc.luau'), join(d, 'wire_model.luau')])).toEqual([]);
  });
});

describe('animate npc', () => {
  it('creates the body, writes the loader, syncs', async () => {
    const codes: string[] = [];
    const c = ctx((code) => (code.includes('CreateHumanoidModelFromDescription') ? { ok: true, path: 'Workspace.Guard' } : {}), codes);
    const r = await call({ action: 'npc', name: 'Guard', rig: 'R15', at: [10, 0, 5] }, c);
    expect(r.text).toMatch(/Workspace\.Guard/);
    expect(readFileSync(join(c.projectPath, MODEL_LOADER_PATH), 'utf8')).toBe(MODEL_LOADER_SOURCE);
    const npc = codes.find((x) => x.includes('CreateHumanoidModelFromDescription'))!;
    expect(npc).toMatch(/"name":"Guard"/);
    expect(npc).not.toMatch(/Name = "Guard"/); // name only in the payload
  });
  it('refuses a bad name, rig or position before touching Studio', async () => {
    const codes: string[] = [];
    const c = ctx(() => ({}), codes);
    expect((await call({ action: 'npc', name: '1bad', rig: 'R15', at: [0, 0, 0] }, c)).isError).toBe(true);
    expect((await call({ action: 'npc', name: 'Guard', rig: 'Workspace.Dog', at: [0, 0, 0] }, c)).isError).toBe(true);
    expect((await call({ action: 'npc', name: 'Guard', rig: 'R15' }, c)).isError).toBe(true);
    expect(codes).toEqual([]);
  });
  it('passes a name clash through without writing the loader', async () => {
    const c = ctx(() => ({ ok: false, code: 'exists', error: 'Workspace already has a Guard' }));
    const r = await call({ action: 'npc', name: 'Guard', rig: 'R15', at: [0, 0, 0] }, c);
    expect(r.isError).toBe(true);
    expect(r.text).toMatch(/already has a Guard/);
    expect(existsSync(join(c.projectPath, MODEL_LOADER_PATH))).toBe(false);
  });
});
