import { describe, it, expect } from 'vitest';
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { applyWire, LOADER_PATH, LOADER_SOURCE, planWire, readSlots, renderSlots, SLOTS_PATH } from '../src/anim/wire.js';

const project = () => mkdtempSync(join(tmpdir(), 'blox-wire-'));
const write = (P: string, rel: string, s: string) => { mkdirSync(dirname(join(P, rel)), { recursive: true }); writeFileSync(join(P, rel), s); };

describe('wire', () => {
  it('first wire writes the loader and the slot table', () => {
    const P = project();
    const p = planWire(P, { slot: 'walk', asset: 507777826 });
    expect(p).toMatchObject({ ok: true, writeLoader: true, slots: { walk: 'rbxassetid://507777826' } });
    if (!p.ok) return;
    applyWire(P, p.slots, p.writeLoader);
    expect(readFileSync(join(P, LOADER_PATH), 'utf8')).toBe(LOADER_SOURCE);
    expect(readSlots(P)).toEqual({ ok: true, slots: { walk: 'rbxassetid://507777826' } });
  });

  it('normalizes every id form and refuses junk', () => {
    const P = project();
    for (const a of ['123', 'rbxassetid://123', 'https://www.roblox.com/asset/?id=123', 123]) expect(planWire(P, { slot: 'run', asset: a })).toMatchObject({ ok: true, slots: { run: 'rbxassetid://123' } });
    for (const a of [0, 'abc', '', -5, 1.5]) expect(planWire(P, { slot: 'run', asset: a }).ok).toBe(false);
  });

  it('replacing a filled slot needs replaces: <current id>', () => {
    const P = project();
    applyWire(P, { walk: 'rbxassetid://1' }, true);
    expect(planWire(P, { slot: 'walk', asset: 2 })).toMatchObject({ ok: false, error: expect.stringMatching(/replaces/) });
    expect(planWire(P, { slot: 'walk', asset: 2, replaces: 9 })).toMatchObject({ ok: false, error: expect.stringMatching(/holds rbxassetid:\/\/1/) });
    expect(planWire(P, { slot: 'walk', asset: 2, replaces: 'rbxassetid://1' })).toMatchObject({ ok: true, writeLoader: false, slots: { walk: 'rbxassetid://2' } });
  });

  it('leaves a hand-edited loader or slot table alone', () => {
    const P = project();
    write(P, LOADER_PATH, LOADER_SOURCE + '\n-- my tweak\n');
    expect(planWire(P, { slot: 'idle', asset: 1 })).toMatchObject({ ok: false, error: expect.stringMatching(/edited by hand.*loader/) });
    const Q = project();
    write(Q, SLOTS_PATH, 'return { walk = "rbxassetid://1" }\n');
    expect(planWire(Q, { slot: 'idle', asset: 1 })).toMatchObject({ ok: false, error: expect.stringMatching(/not generated by blox/) });
  });

  it('renders a parseable, sorted table', () => {
    const s = renderSlots({ walk: 'rbxassetid://2', idle: 'rbxassetid://1' });
    expect(s).toMatch(/^-- GENERATED by blox animate wire/);
    expect(s.indexOf('idle')).toBeLessThan(s.indexOf('walk'));
  });
});

describe('loader', () => {
  it('applies again once the avatar appearance has loaded (it replaces the Animate slot Animations)', () => {
    expect(LOADER_SOURCE).toMatch(/player\.CharacterAppearanceLoaded:Connect\(apply\)/);
    expect(LOADER_SOURCE).toMatch(/player\.CharacterAdded:Connect\(apply\)/);
  });
});

describe('line endings', () => {
  it('accepts its own files after a CRLF checkout (Git for Windows autocrlf)', () => {
    const P = project();
    applyWire(P, { walk: 'rbxassetid://1' }, true);
    for (const rel of [LOADER_PATH, SLOTS_PATH]) writeFileSync(join(P, rel), readFileSync(join(P, rel), 'utf8').replace(/\n/g, '\r\n'));
    expect(readSlots(P)).toEqual({ ok: true, slots: { walk: 'rbxassetid://1' } });
    expect(planWire(P, { slot: 'idle', asset: 2 })).toMatchObject({ ok: true, writeLoader: false });
  });
});
