import type { HookCallback, HookInput, HookJSONOutput } from '@anthropic-ai/claude-agent-sdk';
import { syncProject, realSpawn, type SpawnFn } from '../sync/rojo.js';

export const EXECUTE_LUAU_TOOL = 'mcp__Roblox_Studio__execute_luau';
export const GEN_MESH_TOOL = 'mcp__Roblox_Studio__generate_mesh';
export const WAIT_JOB_TOOL = 'mcp__Roblox_Studio__wait_job_finished';

// How the result hook reaches the panel's gate broker (mirrors GateChannel in
// permission.ts: connectivity check + an awaitable decision).
export interface ResultGateChannel {
  isConnected(): boolean;
  requestResult(
    tool: string,
    tag: string | null,
    inputSummary: string,
  ): Promise<{ decision: 'approve' | 'reject'; source: 'dock' | 'timeout'; feedback?: string }>;
}

const TAG_RE = /Assistant-[A-Za-z]+-[0-9a-fA-F][0-9a-fA-F-]{7,}/;

// JSON-decode every MCP text block in a tool response (non-JSON blocks skipped).
function textBlockJson(response: unknown): Record<string, unknown>[] {
  const out: Record<string, unknown>[] = [];
  const content = (response as { content?: unknown } | null)?.content;
  if (!Array.isArray(content)) return out;
  for (const b of content as { type?: unknown; text?: unknown }[]) {
    if (b?.type === 'text' && typeof b.text === 'string') {
      try {
        const j = JSON.parse(b.text) as unknown;
        if (j && typeof j === 'object') out.push(j as Record<string, unknown>);
      } catch {
        // not JSON — the regex fallback below handles it
      }
    }
  }
  return out;
}

// Both result shapes live-probed (Task 1, 2026-06-12):
//   generate_mesh      → {"tag":"Assistant-MeshGen-<uuid>"} — instance name.
//   wait_job_finished  → {"modelFullName":"Workspace.SmallGrayRock",
//                         "resultName":"SmallGrayRock","status":"Completed",...}
//     — the procedural instance is named from the PROMPT, not Assistant-tagged.
// Parse JSON first; the Assistant-* regex is a defensive fallback for shapes
// a future Studio build might introduce.
export function extractAssetTag(response: unknown): string | null {
  for (const j of textBlockJson(response)) {
    if (typeof j.tag === 'string') return j.tag;
    if (j.status === 'Completed' && typeof j.resultName === 'string') return j.resultName;
  }
  let s: string;
  try {
    s = JSON.stringify(response) ?? '';
  } catch {
    s = String(response);
  }
  return s.match(TAG_RE)?.[0] ?? null;
}

// True only when the response provably reports a non-Completed job: nothing
// landed in the DataModel, so there is no result to gate. Unknown shapes
// return false (gate defensively rather than silently skip).
export function jobLandedNothing(response: unknown): boolean {
  return textBlockJson(response).some((j) => typeof j.status === 'string' && j.status !== 'Completed');
}

export function rejectMessage(toolName: string, stashed: boolean, feedback?: string): string {
  return (
    `The user rejected the asset generated by "${toolName}"` +
    (stashed ? ' and it was moved to ReplicatedStorage._bloxRejected' : '') +
    '. ' +
    (feedback ? `User feedback: ${feedback}. ` : '') +
    'Adjust your approach based on this or continue without the asset. Do not re-insert the rejected asset.'
  );
}

// PostToolUse result gate (P2 spec §3-4): after an asset generation lands,
// park the run on the dock's approve/reject card. Approve (and timeout, and
// every degraded path) continues; reject blocks with the user's feedback so
// the agent can adjust. Never calls MCP (SP1c-d single-client rule) and never
// stalls the run on a broken channel.
export function buildAssetResultHook(gate?: ResultGateChannel): HookCallback {
  return async (input: HookInput): Promise<HookJSONOutput> => {
    if (input.hook_event_name !== 'PostToolUse') return { continue: true };
    if (input.tool_name !== GEN_MESH_TOOL && input.tool_name !== WAIT_JOB_TOOL) return { continue: true };
    if (!gate?.isConnected()) return { continue: true };
    if (input.tool_name === WAIT_JOB_TOOL && jobLandedNothing(input.tool_response)) return { continue: true };

    const tag = extractAssetTag(input.tool_response);
    try {
      const inputSummary = JSON.stringify(input.tool_input ?? {}).slice(0, 200);
      const d = await gate.requestResult(input.tool_name, tag, inputSummary);
      if (d.decision === 'reject') {
        return { decision: 'block', reason: rejectMessage(input.tool_name, tag !== null, d.feedback) };
      }
    } catch {
      // A broken channel must never stall the run — fall through to continue.
    }
    return { continue: true };
  };
}

// PreToolUse gate: push .luau files to Studio via Rojo before the agent runs
// Luau tests, so execute_luau always sees current files. blox owns sync; the
// agent owns when/what to test.
export function buildSyncHook(projectPath: string, spawn: SpawnFn = realSpawn): HookCallback {
  return async (input: HookInput): Promise<HookJSONOutput> => {
    if (input.hook_event_name !== 'PreToolUse') return { continue: true };
    if (input.tool_name !== EXECUTE_LUAU_TOOL) return { continue: true };

    const res = await syncProject(projectPath, spawn);
    if (res.ok) return { continue: true };

    return {
      continue: true,
      hookSpecificOutput: {
        hookEventName: 'PreToolUse',
        additionalContext: `Rojo sync failed before running tests: ${res.detail}. Files may be stale in Studio.`,
      },
    };
  };
}
