import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { longString } from '../studio/luau.js';
import { RESOLVE_LUAU } from './modelRig.js';
import type { ModelState } from './animation-tool.js';


// NPCs and models are animated by one server Script in the project: it plays
// each tagged model's idle, walk and run by how fast the model moves, from the
// model's attributes. Clones carry the tag and attributes, so spawners need
// nothing else. Port of Roqer's RoqerModelAnimate, retargeted from one script
// per model to a tag.
export const MODEL_LOADER_PATH = 'src/ServerScriptService/BloxModelAnimate.server.luau';
export const MODEL_TAG = 'BloxAnimated';

export const MODEL_LOADER_SOURCE = `-- GENERATED by blox animate (BloxModelAnimate 1). Edit with animate {action:"wire"}; hand edits stop blox managing it.
-- Plays the idle, walk and run animations of every model tagged BloxAnimated,
-- by how fast the model moves. They are the model's attributes: BloxAnim_idle,
-- BloxAnim_walk and BloxAnim_run hold animation ids, and BloxAnim_walkSpeed and
-- BloxAnim_runSpeed the ground speed in studs a second each was written for,
-- so its feet keep pace.
local CollectionService = game:GetService("CollectionService")
local RunService = game:GetService("RunService")

local TAG = "${MODEL_TAG}"
local PRIORITY = {
	idle = Enum.AnimationPriority.Idle,
	walk = Enum.AnimationPriority.Movement,
	run = Enum.AnimationPriority.Movement,
}
-- Seconds to cross-fade from one state to the next.
local FADE = 0.2
-- Studs a second below which the model stands.
local STANDING = 0.5
-- How far a gait may be slowed down or sped up to keep pace with the model.
local SLOWEST, FASTEST = 0.5, 2

local active = {}

local function attach(model)
	if active[model] or not model:IsA("Model") then
		return
	end
	local humanoid = model:FindFirstChildOfClass("Humanoid")
	local controller = humanoid or model:FindFirstChildOfClass("AnimationController")
	if not controller then
		warn("BloxModelAnimate: " .. model:GetFullName() .. " has no Humanoid or AnimationController to animate")
		return
	end
	local animator = controller:FindFirstChildOfClass("Animator")
	if not animator then
		animator = Instance.new("Animator")
		animator.Parent = controller
	end
	local state = { tracks = {}, current = nil, running = 0, measured = 0, last = nil, connections = {} }
	active[model] = state

	local function load(name)
		local old = state.tracks[name]
		if old then
			old:Stop(0)
			old:Destroy()
			state.tracks[name] = nil
		end
		if state.current == name then
			state.current = nil
		end
		local id = model:GetAttribute("BloxAnim_" .. name)
		if typeof(id) ~= "string" or id == "" then
			return
		end
		local animation = Instance.new("Animation")
		animation.AnimationId = id
		local ok, track = pcall(animator.LoadAnimation, animator, animation)
		if not ok then
			warn("BloxModelAnimate: " .. model:GetFullName() .. "'s " .. name .. " animation " .. id .. " did not load: " .. tostring(track))
			return
		end
		track.Priority = PRIORITY[name]
		track.Looped = true
		state.tracks[name] = track
	end
	for name in PRIORITY do
		load(name)
	end
	table.insert(state.connections, model.AttributeChanged:Connect(function(attribute)
		local name = string.match(attribute, "^BloxAnim_(%a+)$")
		if name and PRIORITY[name] then
			load(name)
		end
	end))
	if humanoid then
		table.insert(state.connections, humanoid.Running:Connect(function(speed)
			state.running = speed
		end))
	end
end

local function detach(model)
	local state = active[model]
	if not state then
		return
	end
	active[model] = nil
	for _, connection in state.connections do
		connection:Disconnect()
	end
	for _, track in state.tracks do
		track:Stop(0)
		track:Destroy()
	end
end

local function choose(model, state, speed)
	if speed < STANDING then
		return "idle"
	end
	local walkSpeed, runSpeed = model:GetAttribute("BloxAnim_walkSpeed"), model:GetAttribute("BloxAnim_runSpeed")
	if state.tracks.walk and state.tracks.run and typeof(walkSpeed) == "number" and typeof(runSpeed) == "number" then
		return if speed > (walkSpeed + runSpeed) / 2 then "run" else "walk"
	end
	return if state.tracks.walk then "walk" elseif state.tracks.run then "run" else "idle"
end

RunService.Heartbeat:Connect(function(dt)
	for model, state in active do
		local speed = state.running
		if not model:FindFirstChildOfClass("Humanoid") then
			-- Anything without a Humanoid is timed from frame to frame.
			local root = model.PrimaryPart
			local position = if root then root.Position else model:GetPivot().Position
			if position and state.last and dt > 0 then
				local moved = (position - state.last) * Vector3.new(1, 0, 1)
				state.measured += (moved.Magnitude / dt - state.measured) * math.min(1, dt * 5)
			end
			state.last = position
			speed = state.measured
		end
		local name = choose(model, state, speed)
		if name ~= state.current then
			local previous = state.current and state.tracks[state.current]
			if previous then
				previous:Stop(FADE)
			end
			if state.tracks[name] then
				state.tracks[name]:Play(FADE)
			end
			state.current = name
		end
		local track = state.tracks[name]
		local written = model:GetAttribute("BloxAnim_" .. name .. "Speed")
		if track and name ~= "idle" and typeof(written) == "number" and written > 0 then
			track:AdjustSpeed(math.clamp(speed / written, SLOWEST, FASTEST))
		end
	end
end)

CollectionService:GetInstanceAddedSignal(TAG):Connect(attach)
CollectionService:GetInstanceRemovedSignal(TAG):Connect(detach)
for _, model in CollectionService:GetTagged(TAG) do
	task.spawn(attach, model)
end
`;

export function planModelLoader(projectPath: string): { ok: true; write: boolean } | { ok: false; error: string } {
  const f = join(projectPath, MODEL_LOADER_PATH);
  if (!existsSync(f)) return { ok: true, write: true };
  if (readFileSync(f, 'utf8').replace(/\r\n/g, '\n') !== MODEL_LOADER_SOURCE) return { ok: false, error: `${MODEL_LOADER_PATH} was edited by hand, so blox leaves it alone; restore it (delete the file and run npc or wire again) to let blox manage models` };
  return { ok: true, write: false };
}

export function writeModelLoader(projectPath: string): void {
  const f = join(projectPath, MODEL_LOADER_PATH);
  mkdirSync(dirname(f), { recursive: true });
  writeFileSync(f, MODEL_LOADER_SOURCE);
}

export const NPC_NAME = /^[A-Za-z][A-Za-z0-9_ -]{0,63}$/;

// A stock body, without the LocalScript Animate (which runs only under a
// player), tagged for the loader, its feet on P.at; one undo step.
const NPC_LUAU = `local parent = resolve(P.parent)
if not parent then return HS:JSONEncode({ ok = false, code = "not_found", error = P.parent .. " does not exist" }) end
if not (parent == workspace or parent:IsDescendantOf(workspace)) then return HS:JSONEncode({ ok = false, code = "bad_location", error = "an NPC goes under Workspace" }) end
if parent:FindFirstChild(P.name) then return HS:JSONEncode({ ok = false, code = "exists", error = parent:GetFullName() .. " already has a " .. P.name }) end
local CHS = game:GetService("ChangeHistoryService")
local rec
pcall(function() rec = CHS:TryBeginRecording("blox animate npc") end)
local ok, res = pcall(function()
	local rig = game:GetService("Players"):CreateHumanoidModelFromDescription(Instance.new("HumanoidDescription"), P.rig == "R6" and Enum.HumanoidRigType.R6 or Enum.HumanoidRigType.R15)
	rig.Name = P.name
	local animate = rig:FindFirstChild("Animate")
	if animate then animate:Destroy() end
	rig:AddTag("${MODEL_TAG}")
	rig:PivotTo(CFrame.new(P.at[1], P.at[2], P.at[3]))
	local box, size = rig:GetBoundingBox()
	rig:PivotTo(rig:GetPivot() + Vector3.new(0, P.at[2] - (box.Position.Y - size.Y / 2), 0))
	rig.Parent = parent
	return rig:GetFullName()
end)
if rec then pcall(function() CHS:FinishRecording(rec, ok and Enum.FinishRecordingOperation.Commit or Enum.FinishRecordingOperation.Cancel) end) end
if not ok then return HS:JSONEncode({ ok = false, error = tostring(res) }) end
return HS:JSONEncode({ ok = true, path = res })`;

export function npcProgram(o: { name: string; rig: 'R15' | 'R6'; at: [number, number, number]; parent: string }): string {
  return `local PAYLOAD = ${longString(JSON.stringify(o))}
local HS = game:GetService("HttpService")
local P = HS:JSONDecode(PAYLOAD)
${RESOLVE_LUAU}${NPC_LUAU}`;
}


const WIRE_MODEL_LUAU = `-- BloxAnimWire
local model, controller, err = animatedModel(P.path)
if not model then return HS:JSONEncode({ ok = false, code = controller, error = err }) end
local humanoid = controller:IsA("Humanoid") and controller or nil
if P.rigType and (not humanoid or humanoid.RigType.Name ~= P.rigType) then
	return HS:JSONEncode({ ok = false, code = "rig", error = model:GetFullName() .. " is " .. (humanoid and ("an " .. humanoid.RigType.Name .. " Humanoid") or "not a Humanoid") .. "; this is an " .. P.rigType .. " animation" })
end
local key = "BloxAnim_" .. P.state
local held = model:GetAttribute(key)
if typeof(held) == "string" and held ~= "" and held ~= P.id and not table.find(P.allowed, held) and not P.force then
	return HS:JSONEncode({ ok = false, code = "held", held = held, error = model:GetFullName() .. " " .. key .. " holds " .. held })
end
local CHS = game:GetService("ChangeHistoryService")
local rec
pcall(function() rec = CHS:TryBeginRecording("blox animate wire") end)
model:SetAttribute(key, P.id)
if P.state ~= "idle" then model:SetAttribute(key .. "Speed", P.speed) end
model:AddTag("${MODEL_TAG}")
if rec then pcall(function() CHS:FinishRecording(rec, Enum.FinishRecordingOperation.Commit) end) end
return HS:JSONEncode({ ok = true, path = model:GetFullName(), held = held, walkSpeed = humanoid and humanoid.WalkSpeed or nil })`;

export function wireModelProgram(o: { path: string; state: ModelState; id: string; speed: number | null; allowed: string[]; force: boolean; rigType: 'R15' | 'R6' | null }): string {
  return `local PAYLOAD = ${longString(JSON.stringify(o))}
local HS = game:GetService("HttpService")
local P = HS:JSONDecode(PAYLOAD)
${RESOLVE_LUAU}${WIRE_MODEL_LUAU}`;
}

type Wired = Record<string, Partial<Record<ModelState, string>>>;
const wiredFile = (projectPath: string) => join(projectPath, '.blox', 'anims', 'wired.json');

export function readWired(projectPath: string): Wired {
  const f = wiredFile(projectPath);
  return existsSync(f) ? (JSON.parse(readFileSync(f, 'utf8')) as Wired) : {};
}

export function saveWired(projectPath: string, wired: Wired): void {
  mkdirSync(dirname(wiredFile(projectPath)), { recursive: true });
  writeFileSync(wiredFile(projectPath), JSON.stringify(wired, null, 2));
}

// Project scripts that already play animations on this model (by its name):
// with the loader too, two scripts load tracks on one Animator and fight.
export function otherAnimators(projectPath: string, modelName: string): string[] {
  const root = join(projectPath, 'src');
  if (!existsSync(root) || !modelName) return [];
  const out: string[] = [];
  const name = new RegExp(`["'.]${modelName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`);
  const walk = (d: string) => {
    for (const e of readdirSync(d)) {
      const f = join(d, e);
      if (statSync(f).isDirectory()) walk(f);
      else if (/\.luau?$/.test(e)) {
        const rel = relative(projectPath, f).split(sep).join('/');
        if (rel === MODEL_LOADER_PATH) continue;
        const src = readFileSync(f, 'utf8');
        if (name.test(src) && /:LoadAnimation\(/.test(src)) out.push(rel);
      }
    }
  };
  walk(root);
  return out.sort();
}
