import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { ANIMATE_SLOTS, normalizeAnimationId, type AnimateSlot } from './animation-tool.js';

// Wiring is two project files: a fixed loader that never changes and a
// generated slot table. Sync ships both; nothing is written into Studio here.
export const LOADER_PATH = 'src/ServerScriptService/BloxCharacterAnimate.server.luau';
export const SLOTS_PATH = 'src/ReplicatedStorage/BloxAnimSlots.luau';
const HEADER = '-- GENERATED by blox animate wire. Edit with animate {action:"wire"}; hand edits stop blox managing it.';

export const LOADER_SOURCE = `-- Built by blox (animate wire). Sets each character's default Animate script
-- to the animation ids in ReplicatedStorage.BloxAnimSlots, one per slot (idle,
-- walk, run, jump, fall, climb, swim, swimidle, sit). The ids change; this code
-- does not.
local Players = game:GetService("Players")
local slots = require(game:GetService("ReplicatedStorage"):WaitForChild("BloxAnimSlots"))

local function apply(character)
	local animate = character:WaitForChild("Animate", 10)
	if not animate then
		return
	end
	for slot, id in slots do
		local folder = animate:FindFirstChild(slot)
		if folder then
			for _, child in folder:GetChildren() do
				if child:IsA("Animation") then
					child.AnimationId = id
				end
			end
		end
	end
end

local function watch(player)
	player.CharacterAdded:Connect(apply)
	if player.Character then
		task.spawn(apply, player.Character)
	end
end

Players.PlayerAdded:Connect(watch)
for _, player in Players:GetPlayers() do
	watch(player)
end
`;

type Slots = Partial<Record<AnimateSlot, string>>;

export function readSlots(projectPath: string): { ok: true; slots: Slots } | { ok: false; error: string } {
  const f = join(projectPath, SLOTS_PATH);
  if (!existsSync(f)) return { ok: true, slots: {} };
  const text = readFileSync(f, 'utf8');
  if (!text.startsWith(HEADER)) return { ok: false, error: `${SLOTS_PATH} was not generated by blox (or was edited); move your changes out and delete it, then wire again` };
  const slots: Slots = {};
  for (const m of text.matchAll(/^\t(\w+) = "(rbxassetid:\/\/\d+)",$/gm)) {
    if (!(ANIMATE_SLOTS as readonly string[]).includes(m[1])) return { ok: false, error: `${SLOTS_PATH} names an unknown slot ${m[1]}` };
    slots[m[1] as AnimateSlot] = m[2];
  }
  if (renderSlots(slots) !== text) return { ok: false, error: `${SLOTS_PATH} was edited by hand; restore it or delete it, then wire again` };
  return { ok: true, slots };
}

export function renderSlots(slots: Slots): string {
  const lines = ANIMATE_SLOTS.filter((s) => slots[s]).map((s) => `\t${s} = "${slots[s]}",`);
  return `${HEADER}\nreturn {\n${lines.join('\n')}${lines.length ? '\n' : ''}}\n`;
}

export function planWire(projectPath: string, o: { slot: AnimateSlot; asset: unknown; replaces?: unknown }): { ok: true; slots: Slots; writeLoader: boolean } | { ok: false; error: string } {
  const id = normalizeAnimationId(o.asset);
  if (!id) return { ok: false, error: `asset must be an asset id (123, rbxassetid://123 or a roblox.com asset link); got ${JSON.stringify(o.asset)}` };
  const loader = join(projectPath, LOADER_PATH);
  const writeLoader = !existsSync(loader);
  if (!writeLoader && readFileSync(loader, 'utf8') !== LOADER_SOURCE) return { ok: false, error: `${LOADER_PATH} was edited by hand, so blox leaves the loader alone; restore it (delete the file and wire again) to let blox manage slots` };
  const cur = readSlots(projectPath);
  if (!cur.ok) return cur;
  const held = cur.slots[o.slot];
  if (held && held !== id) {
    if (o.replaces === undefined) return { ok: false, error: `slot ${o.slot} holds ${held}; pass replaces:"${held}" to replace it` };
    if (normalizeAnimationId(o.replaces) !== held) return { ok: false, error: `slot ${o.slot} holds ${held}, not ${JSON.stringify(o.replaces)}` };
  }
  return { ok: true, slots: { ...cur.slots, [o.slot]: id }, writeLoader };
}

export function applyWire(projectPath: string, slots: Slots, writeLoader: boolean): void {
  for (const [rel, text] of [[SLOTS_PATH, renderSlots(slots)], ...(writeLoader ? [[LOADER_PATH, LOADER_SOURCE]] : [])] as [string, string][]) {
    const f = join(projectPath, rel);
    mkdirSync(dirname(f), { recursive: true });
    writeFileSync(f, text);
  }
}
